/// @description 메뉴 열거
draw_set_font(fontEditorBold)
var menu_file = editor_menu_add("파일", "파일 메뉴", editor_callback_menu_cursor)
editor_submenu_add(menu_file, "", sEditorNew, -1)
editor_submenu_add(menu_file, "", sEditorOpen, -1)
editor_submenu_add(menu_file, "", sEditorSave, editor_save)
var menu_node = editor_menu_add("노드", "노드 추가 및 삭제하기", editor_callback_menu_node)
editor_submenu_add(menu_node, "모든 노드 삭제", sEditorClearNodes, editor_callback_node_clear_all)
var menu_sprite = editor_menu_add("스프라이트 타일", "타일 배치하기", editor_callback_menu_tile)
editor_submenu_add(menu_sprite, "모든 타일 삭제", sEditorClearTiles, editor_callback_tile_clear_all)
var menu_doodad = editor_menu_add("장식물", "장식물 배치하기", editor_callback_menu_doodad)
editor_submenu_add(menu_doodad, "모든 장식물 삭제", sEditorClearObstacles, editor_callback_doodad_clear_all)
var menu_instance = editor_menu_add("개체", "상호작용 개체 배치하기", editor_callback_menu_object)
editor_submenu_add(menu_instance, "모든 개체 삭제", sEditorClearObjects, editor_callback_entity_clear_all)
var menu_setting = editor_menu_add("설정", "설정", editor_callback_menu_setting)
editor_submenu_add(menu_setting, "격자 끄기", sEditorOptionGrid, editor_callback_grid_off)
editor_submenu_add(menu_setting, "하양색", sEditorOptionGridInverse, editor_callback_grid_inverse)
editor_submenu_add(menu_setting, "노랑색", sEditorOptionGridYellow, editor_callback_grid_yellow)
editor_submenu_add(menu_setting, "빨강색", sEditorOptionGridRed, editor_callback_grid_red)
editor_submenu_add(menu_setting, "회색", sEditorOptionGridWhite, editor_callback_grid_white)
draw_set_font(fontEditor)
